## In this directory, run the following command to build this builder.
## $ `gcloud builds submit --config=cloudbuild.yaml .`

steps:
- name: 'gcr.io/cloud-builders/wget'
  args: ["https://releases.hashicorp.com/terraform/${_TERRAFORM_VERSION}/terraform_${_TERRAFORM_VERSION}_linux_amd64.zip"]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/terraform:${_TERRAFORM_VERSION}',
        '-t', 'gcr.io/$PROJECT_ID/terraform',
        '--build-arg', 'TERRAFORM_VERSION=${_TERRAFORM_VERSION}',
        '--build-arg', 'TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM}',
        '.']
substitutions:
  _TERRAFORM_VERSION: 0.13.6
  _TERRAFORM_VERSION_SHA256SUM: 55f2db00b05675026be9c898bdd3e8230ff0c5c78dd12d743ca38032092abfc9

images:
- 'gcr.io/$PROJECT_ID/terraform:latest'
- 'gcr.io/$PROJECT_ID/terraform:${_TERRAFORM_VERSION}'
tags: ['cloud-builders-community']
